import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AuthContext from "@/context/AuthContext";
import Footer from "@/components/footer";
import NavBar from "@/components/navigation";
const inter = Inter({ subsets: ["latin"] });
require("dotenv").config();

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const scriptKey = process.env.GOOGLE_API;
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthContext>
          <NavBar />
          {children}
          <div className="h-10 mb-10"></div>
          <Footer />
          <script async src={scriptKey}></script>
        </AuthContext>
      </body>
    </html>
  );
}
