// pages/index.tsx
"use client";
import React from "react";
import Head from "next/head";
import BusList from "@/components/buslist";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { useSearchParams } from "next/navigation";

// const buses = [
//   {
//     id: 1,
//     name: "Example Bus 1",
//     route: "Source to Destination",
//     departureTime: "08:00 AM",
//     arrivalTime: "12:00 PM",
//     fare: "$30",
//     dateOfBoarding: "2024-02-21",
//   },
//   {
//     id: 2,
//     name: "Example Bus 2",
//     route: "Source to Destination",
//     departureTime: "10:00 AM",
//     arrivalTime: "02:00 PM",
//     fare: "$35",
//     dateOfBoarding: "2024-02-21",
//   },
//   {
//     id: 3,
//     name: "Example Bus 3",
//     route: "Source to Destination",
//     departureTime: "10:00 AM",
//     arrivalTime: "02:00 PM",
//     fare: "$35",
//     dateOfBoarding: "2024-02-21",
//   },
// ];

const HomePage = () => {
  const router = useRouter();
  const searchParams = useSearchParams();

  const search = searchParams.get("buses");
  const source = searchParams.get("source");
  const destination = searchParams.get("destination");
  const date = searchParams.get("date");

  const parsedSearch = JSON.parse(search);

  console.log(parsedSearch);
  return (
    <>
      <Head>
        <title>Bus Search Results</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-4xl font-semibold text-center pt-10">
        Bus Search Results
      </h1>
      <BusList buses={parsedSearch.data} source={source} destination={destination} date={date} />
    </>
  );
};

export default HomePage;
